sudo: required
services:
  - docker

before_install:
  - docker build -t hamdan2018/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamdan2018/react-test npm test -- --coverage

after_success:
  - docker build -t hamdan2018/multi-client ./client
  - docker build -t hamdan2018/multi-nginx ./nginx
  - docker build -t hamdan2018/multi-server ./server
  - docker build -t hamdan2018/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push hamdan2018/multi-client
  - docker push hamdan2018/multi-nginx
  - docker push hamdan2018/multi-server
  - docker push hamdan2018/multi-worker